In [ ]:
import numpy as np

Addition

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[1,2,3]])
new_arr=np.add(arr1,arr2)
print(new_arr)

[[ 8 10 12]
 [ 5  7  9]]


Subtraction

In [ ]:
arr1=np.array([[10,17,18],[28,25,6]])
arr2=np.array([[7,8,3],[8,12,2]])
new_arr=np.subtract(arr1,arr2)
print(new_arr)

[[ 3  9 15]
 [20 13  4]]


Multipication

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[1,2,3]])
new_arr=np.multiply(arr1,arr2)
print(new_arr)

[[ 7 16 27]
 [ 4 10 18]]


Division

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[1,2,3]])
new_arr=np.divide(arr1,arr2)
print(new_arr)

[[0.14285714 0.25       0.33333333]
 [4.         2.5        2.        ]]


Transpose of a matric

In [ ]:
a=np.array([[[1,2],[3,4]],[[1,3],[2,4]]])
print(a)
print(np.transpose(a))

[[[1 2]
  [3 4]]

 [[1 3]
  [2 4]]]
[[[1 1]
  [3 2]]

 [[2 3]
  [4 4]]]


In [ ]:
arr=np.array([[2,3,4],[1,7,8]])
print(arr)
print(np.transpose(arr))

[[2 3 4]
 [1 7 8]]
[[2 1]
 [3 7]
 [4 8]]


In [ ]:
m=np.array([[1,2,3],[4,5,6]])
n=np.array([[1,7,9],[2,3,4]])
print("addition\n",np.add(m,n))
print("subtraction\n",np.subtract(m,n))
print("multiple\n",np.multiply(m,n))
print("division\n",np.divide(m,n))
print("Transpose of 1st\n",np.transpose(m))
print("Transpose of 2nd\n",np.transpose(n))

addition
 [[ 2  9 12]
 [ 6  8 10]]
subtraction
 [[ 0 -5 -6]
 [ 2  2  2]]
multiple
 [[ 1 14 27]
 [ 8 15 24]]
division
 [[1.         0.28571429 0.33333333]
 [2.         1.66666667 1.5       ]]
Transpose of 1st
 [[1 4]
 [2 5]
 [3 6]]
Transpose of 2nd
 [[1 2]
 [7 3]
 [9 4]]


In [ ]:
m=np.array([[1,2],[3,4]])
n=np.array([[4,5],[7,3]])
print(m)
print(n)
print(np.matmul(m,n))


[[1 2]
 [3 4]]
[[4 5]
 [7 3]]
[[18 11]
 [40 27]]


In [ ]:
a=np.array([[[1,2],[3,4]],[[1,3],[2,4]]])
b=np.array([[[2,3],[2,1]],[[4,5],[8,5]]])
print(np.matmul(a,b))

[[[ 6  5]
  [14 13]]

 [[28 20]
  [40 30]]]


Question

In [ ]:
arr=np.zeros((6,6),dtype="int")
arr[1:5,1:5]=1
arr[2:4,2:4]=2
print(arr)

[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 2 2 1 0]
 [0 1 2 2 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


In [ ]:
arr=np.zeros((5,6),dtype="int")
arr[::4,::5]=1
arr[1::2,1::3]=1
arr[2,2:4]=1
print(arr)

[[1 0 0 0 0 1]
 [0 1 0 0 1 0]
 [0 0 1 1 0 0]
 [0 1 0 0 1 0]
 [1 0 0 0 0 1]]


In [ ]:
arr=np.zeros((5,5),dtype="int")
arr[::4,::4]=8
arr[1::2,1::2]=8
arr[2,2]=8
print(arr)

[[8 0 0 0 8]
 [0 8 0 8 0]
 [0 0 8 0 0]
 [0 8 0 8 0]
 [8 0 0 0 8]]


In [ ]:
arr=np.array([[[1,2,3,4],[6,7,8,9]],[[4,6,7,8],[9,0,4,6]],[[4,5,7,8],[6,9,7,0]]])
print(arr[0,0,0:2])
print(arr[1,0,0:2])


[1 2]
[4 6]
