In [ ]:
import numpy as np
array=np.arange(0,10,2)
print(array)

[0 2 4 6 8]


In [ ]:
import numpy as np
array2=np.arange(2,22,2)
print(array2)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#Printing all numbers from 1 to2 in steps of 0.1
import numpy as np
array1=np.arange(1,2,0.1)
print(array1)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [ ]:
#Write a program to to create 3X3 matrix with values rangeing from 1 to 10

import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
