In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

Copy

In [ ]:
x=arr.copy()
arr[0]=42
x[3]=12
print(arr)
print(x)

[42  2  3  4  5]
[ 1  2  3 12  5]


View

In [ ]:
y=arr.view()
y[3]=34
print(y)
print(arr)

[42  2  3 34  5]
[42  2  3 34  5]


In [ ]:
print(x.base)

None


In [ ]:
print(y.base)

[42  2  3 34  5]


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_ar=arr1.reshape(2,2,-1)
print(new_ar)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Flattening of arrays

In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr =arr2.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
for i in np.nditer(arr2):
    print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
arr=np.array([1,2,3,4,5])
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1=arr1.reshape(-1)
for i in np.nditer(arr1[::2]):
    print(i)


1
3
5


Enumerated Iteration

In [ ]:
arr = np.array([1,2,3])
for i,x in np.ndenumerate(arr):
    print(i,x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
arr = np.array([[1,2,3],[5,6,7]])
for i,x in np.ndenumerate(arr):
    print(i,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 5
(1, 1) 6
(1, 2) 7


Numpy Joining Array

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
new_arr=np.concatenate((arr1,arr2))
print(new_arr)

[1 2 3 4 5 6]


In [ ]:
arr1=np.array([[1,2,3],[8,9,10]])
arr2=np.array([[4,5,6,],[11,12,13]])
new_arr=np.concatenate((arr1,arr2),axis=1)
print(new_arr)

[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 13]]
