In [ ]:
import numpy as np

Concatenation

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[6,5,3]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 7 8 9]
 [4 5 6 6 5 3]]


Stack function

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
arr2=np.array([[[7,8,9],[6,5,3]],[[1,2,3],[4,5,6]]])
arr=np.stack((arr1,arr2),axis=3)
print(arr)

[[[[ 1  7]
   [ 2  8]
   [ 3  9]]

  [[ 4  6]
   [ 5  5]
   [ 6  3]]]


 [[[ 6  1]
   [ 7  2]
   [ 8  3]]

  [[ 9  4]
   [10  5]
   [11  6]]]]


In [ ]:
arr1=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
arr2=np.array([[[7,8,9],[6,5,3]],[[1,2,3],[4,5,6]]])
arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[ 7  8  9]
   [ 6  5  3]]

  [[ 1  2  3]
   [ 4  5  6]]]]


Different type of stack

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
