In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(np.__version__)

1.26.4


In [ ]:
arr.ndim

1

0 dimentional array

In [ ]:
arr1=np.array(15)
arr1


array(15)

In [ ]:
arr1.ndim

0

2 dimentional array

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2.ndim

2

3 dimentional array

In [ ]:
arr3=np.array([[[1,2,10],[3,4,11],[5,6,12]],[[1,2,98],[3,4,76],[5,6,34]]])
arr3.ndim

3

In [ ]:
print(arr3)
arr3.shape

[[[ 1  2 10]
  [ 3  4 11]
  [ 5  6 12]]

 [[ 1  2 98]
  [ 3  4 76]
  [ 5  6 34]]]


(2, 3, 3)

In [ ]:
arr4 =np.array([1,2,3,4,5],ndmin=5)
print(arr4)
print("dimentional=",arr4.ndim)

[[[[[1 2 3 4 5]]]]]
dimentional= 5


In [ ]:
arr = np.array([2,3,4],dtype="float")
arr.dtype

dtype('float64')

In [ ]:
arr.imag

array([0., 0., 0.])

In [ ]:
arr.real

array([2., 3., 4.])

In [ ]:
#to create array of all zeros
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros((2,2,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr.ndim

3

In [ ]:
arr12=np.array([1,2,3,4,5,6])
print(arr12)
print(type(arr12))
print(arr12.ndim)
print(arr12.dtype)
print(arr12.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
int64
(6,)


In [ ]:
arr=np.array([[1,3,5],[7,6,8]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.shape)

[[1 3 5]
 [7 6 8]]
<class 'numpy.ndarray'>
2
int64
(2, 3)


In [ ]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(type(arr3))
print(arr3.ndim)
print(arr3.dtype)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
int64
(2, 2, 3)


In [ ]:
x=np.ones(6)
print(x)

[1. 1. 1. 1. 1. 1.]


In [ ]:
a=np.array([0,1,2,3,4],dtype="bool")
print(a)

[False  True  True  True  True]
