In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
newarr=np.sum([arr1,arr2])
print(newarr)

12


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
newarr=np.sum([arr1,arr2],axis=1)
print(newarr)

[6 6]


Cummulative sum

It means partially adding the elements in array perform sum with the cumsum() function

In [ ]:
arr=np.array([1,2,3])
newarr=np.cumsum(arr)
print(newarr)

[1 3 6]


Numpy products

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=np.prod(arr)
print(newarr)

720


In [ ]:
arr=np.array([1,2,3,6])
arr1=np.array([1,2,3,4])
newarr=np.prod([arr,arr1])
print(newarr)

864


In [ ]:
arr=np.array([1,2,3,6])
arr1=np.array([1,2,3,4])
newarr=np.prod([arr,arr1],axis=0)
print(newarr)

[ 1  4  9 24]


Cummulative product

In [ ]:
arr=np.array([5,6,7,8])
newarr=np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


Numpy differences

In [ ]:
arr=np.array([10,15,25,5])
newarr=np.diff(arr)
print(newarr)

[  5  10 -20]


Numpy logs

In [ ]:
arr=np.arange(1,10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
arr=np.arange(1,10)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


LCM in numpy

In [ ]:
num=4
num1=6
x=np.lcm(num,num1)
print(x)

12


In [ ]:
num=5
num1=8
x=np.lcm(num,num1)
print(x)

40


In [ ]:
arr=np.array([3,6,9])
x=np.lcm.reduce(arr)
print(x)

18


In [ ]:
arr=np.arange(1,11)
x=np.lcm.reduce(arr)
print(x)

2520


GDC in NUmpy

In [ ]:
num1=6
num2=9
x=np.gcd(num1,num2)
print(x)

3


In [ ]:
arr=np.array([20,8,32,36,16])
x=np.gcd.reduce(arr)
print(x)

4


In [ ]:
arr=np.arange(1,10)
x=np.gcd.reduce(arr)
print(x)

1
