Sorting

In [ ]:
import numpy as np

In [ ]:
arr=np.array([5,4,8,6,2,9])
print(np.sort(arr))

[2 4 5 6 8 9]


In [ ]:
arr=np.array(['bannan','apple','cherry'])
print(np.sort(arr))

['apple' 'bannan' 'cherry']


In [ ]:
arr=np.array([[2,1,4],[1,8,3]])
print(arr)
print(np.sort(arr))
arr.sort()
print(arr)

[[2 1 4]
 [1 8 3]]
[[1 2 4]
 [1 3 8]]
[[1 2 4]
 [1 3 8]]


In [ ]:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


                                                            Filtering element

In [ ]:
arr=np.array([41,42,43,44,])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [ ]:
arr=np.random.randint(1,100,40)
filter_array=[]
for element in arr:
    if element>50:
        filter_array.append(True)
    else:
        filter_array.append(False)
new_arr=arr[filter_array]
print(arr)
print(new_arr)

[ 2  8 97 10 48 34 68 26  8 70 43 25 89 21 91 13 74 55 73 13 76 27 78 71
 95 20  6 70 26 39  1 11 76 64 10 77  9 37  4 15]
[97 68 70 89 91 74 55 73 76 78 71 95 70 76 64 77]


In [ ]:
arr=np.random.randint(1,100,40)
filter_array=[]
for element in arr:
    if element%2==0:
        filter_array.append(True)
    else:
        filter_array.append(False)
new_arr=arr[filter_array]
print(arr)
print(new_arr)

[71 94 31 36 26 80 66 18 35  2 62 21 81 67 76  5 46 10 62  1 16 39 79 90
 43 15 27 25 44 10 55 95 29 85 78 48 90  9 55 76]
[94 36 26 80 66 18  2 62 76 46 10 62 16 90 44 10 78 48 90 76]


In [ ]:
arr=np.random.randint(1,100,40)
filter_array=[]
for element in arr:
    if element%10==0:
        filter_array.append(True)
    else:
        filter_array.append(False)
new_arr=arr[filter_array]
print(arr)
print(new_arr)

[76 34 59 13 46 44 88 25  8 31 87 65  5 82 17 99  4 50 84 23 19 65 91 86
 35  9 55  5 74 33 37 91 43 87 73 31 56 94 11 78]
[50]


                                                            Random

In [ ]:
from numpy import random
x=random.randint(100)
print(x)

45


In [ ]:
from numpy import random
x=random.rand(1)
print(x)

[0.48898616]


In [ ]:
x=random.randint(100,size=(5))
print(x)

[52  7 65 78 80]


In [ ]:
x=random.randint(100,size=(3,2))
print(x)

[[25  1]
 [58 93]
 [54 34]]


In [ ]:
arr=np.arange(9)
a=[]
print(arr)
for i in arr:
    if i%2==1:
        a.append(-1)
    else:
        a.append(i)
print()
print(a)



[0 1 2 3 4 5 6 7 8]

[0, -1, 2, -1, 4, -1, 6, -1, 8]


In [ ]:
arr=np.arange(9)
print("1D array=",arr)
arr=arr.reshape(3,3)
print("3D array\n",arr)

1D array= [0 1 2 3 4 5 6 7 8]
3D array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
