Spliting Array

In [ ]:
import numpy as np

In [ ]:
arr= np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5]


In [ ]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
new=np.array_split(arr,3)
print(new)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
arr=np.arange(1,19).reshape(6,3)
print(arr)
newarr=np.array_split(arr,2,axis=1)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr=np.arange(1,19).reshape(6,3)
print(arr)
newarr=np.hsplit(arr,3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr=np.arange(32).reshape(2,4,4)
print(arr)
new=np.hsplit(arr,2)
arr1=np.dsplit(arr,2)
print(arr1)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]]])]


Searching

In [ ]:
arr=np.arange(1,12)
print(arr)
x=np.where(arr==4)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11]
(array([3], dtype=int64),)


In [ ]:
arr=np.arange(12).reshape(3,4)
print(arr)
x=np.where(arr==4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(array([1], dtype=int64), array([0], dtype=int64))


In [ ]:
arr=np.arange(12).reshape(3,2,2)
print(arr)
x=np.where(arr==5)
print(x)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


In [ ]:
arr1=np.array([1,2,3,4,2,5,2,5,7,6,2,0,1,2])
x=np.where(arr1==2)
print(x)

(array([ 1,  4,  6, 10, 13], dtype=int64),)


In [ ]:
arr=np.array([0,1,2,3,4,5,7,8,9,])
x=np.searchsorted(arr,7)
print(x)

6
