In [ ]:
import numpy as np

Numpy ufuncs

In [ ]:
x=[1,2,3,4]
y=[5,6,7,8]
z=np.add(x,y)
print(z)

[ 6  8 10 12]


In [ ]:
x=[[1,2,3,4],[5,6,7,8]]
y=[[5,6,7,8],[6,3,2,7]]
z=np.add(x,y)
print(z)
print(type(np.add))

[[ 6  8 10 12]
 [11  9  9 15]]
<class 'numpy.ufunc'>


In [ ]:
def myadd(x,y):
    return x+y
myadd=np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))
print(type(myadd))

[11 12 13 14]
<class 'numpy.ufunc'>


In [ ]:
def myad(x,y,z):
    return x+y+z
myad=np.frompyfunc(myad,3,1)
print(myad([1,2,3,4],[5,6,7,8],[2,1,4,5]))

[8 9 14 17]


In [ ]:
def mysub(x,y):
    return x-y
mysub=np.frompyfunc(mysub,2,1)
print(mysub([11,32,36,47],[15,26,17,38]))
print(type(mysub))

[-4 6 19 9]
<class 'numpy.ufunc'>


Write a numpy program that create a custom universal function that adds 10 to every element in a numpy array.use this universal function on a 1D array of interger ?

In [ ]:
def myadd(x):
    return x+10
myadd=np.frompyfunc(myadd,1,1)
print(myadd([1,2,3,4]))

[11 12 13 14]


write a numpy prgram that uses the np.sqrt universal function to compute the square root of each element in a 2 dimentional numpy array

In [ ]:
def my(x):
    return np.sqrt(x)
my=np.frompyfunc(my,1,1)
print(my([[4,9,16],[25,36,49]]))

[[2.0 3.0 4.0]
 [5.0 6.0 7.0]]


Write a numpy program that creates a 2d numpy array and 1d array.use the np.add universal function 2 add the 1 dimentional array to each row of 2d array

In [ ]:
def myadd(x,y):
    return np.add(x,y)
myadd=np.frompyfunc(myadd,2,1)
print(myadd([[1,2,3,4],[5,6,7,8]],[1,2,3,4]))

[[2 4 6 8]
 [6 8 10 12]]


Write a numpy prgram  that uses np.multiple universal function to perform element wise multipication of 2 2d array of the same shape

In [ ]:
def un(x,y):
    return np.multiply(x,y)
un=np.frompyfunc(un,2,1)
print(un([[1,2,3,4],[5,6,7,8]],[[8,7,6,5],[4,3,2,1]]))

[[8 14 18 20]
 [20 18 14 8]]


In [ ]:
if type(np.add)==np.ufunc:
    print("add is ufunc")
else:
    print("add is not ufunc")

add is ufunc


In [ ]:
from numpy import random
x=random.randint(1,5,5)
y=random.randint(1,5,5)
z=np.add(x,y)
print(y)
print(x)
print(z)

[2 4 3 1 4]
[3 1 4 1 1]
[5 5 7 2 5]


In [ ]:
from numpy import random
x=random.randint(1,20,5)
y=random.randint(1,5,5)
z=np.subtract(x,y)
print(y)
print(x)
print(z)

[2 2 4 4 4]
[ 4  8 11 12  7]
[2 6 7 8 3]


In [ ]:
from numpy import random
x=random.randint(1,20,5)
y=random.randint(1,5,5)
z=np.multiply(x,y)
print(y)
print(x)
print(z)

[2 2 1 4 1]
[14 10 10 11 18]
[28 20 10 44 18]


In [ ]:
from numpy import random
x=random.randint(1,20,5)
y=random.randint(1,5,5)
z=np.power(x,y)
print(y)
print(x)
print(z)

[4 3 2 4 3]
[ 2 12 11 15 14]
[   16  1728   121 50625  2744]


In [ ]:
x=random.randint(1,20,5)
y=random.randint(1,5,5)
z=np.mod(x,y)
print(y)
print(x)
print(z)

[2 2 1 2 3]
[ 1  7 13  2 18]
[1 1 0 0 0]


In [ ]:
x=random.randint(1,20,5)
y=random.randint(2,10,5)
z=np.divmod(x,y)
print(y)
print(x)
print(z)

[6 8 9 3 4]
[ 6  8 13 17  4]
(array([1, 1, 1, 5, 1]), array([0, 0, 4, 2, 0]))


Write a numpy program that creates a custom universal function that compute x^2+2x+1 for each element in a numpy array

In [ ]:
def myadd(x):
    return (x**2)+(2*x+1)
myadd=np.frompyfunc(myadd,1,1)
print(myadd([8,2,3,4]))

[81 9 16 25]


In [ ]:
x=[1,2,-3,-4,-8,-5,3,6,7]
newarr=np.absolute(x)
print(newarr)

[1 2 3 4 8 5 3 6 7]


Rounding

In [ ]:
arr=np.trunc([-3.63133,3.68768713])
print(arr)

[-3.  3.]


In [ ]:
arr=np.fix([-3.13133,3.98768713])
print(arr)

[-3.  3.]


In [ ]:
arr=np.floor([-3.1245,4.2443])
print(arr)

[-4.  4.]


In [ ]:
arr=np.ceil([-3.1245,4.2443])
print(arr)

[-3.  5.]


Sum

In [ ]:
arr1=[1,2,3,4]
arr2=[1,2,3,4]
newarr=np.sum([arr1,arr2])
print(newarr)

20
