In [ ]:
import numpy as np
arr=np.zeros(25)
arr=arr.reshape(5,5)
arr[0,:]=1
arr[4,:]=1
arr[:,0]=1
arr[:,4]=1
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x=np.zeros((8,8))
x[1::2, ::2]=1
x[::2,1::2] =1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
a=np.zeros((4,6))
a[::2,2:4]=1
a[1::2,0:2]=1
a[1::2,4::]=1
a

array([[0., 0., 1., 1., 0., 0.],
       [1., 1., 0., 0., 1., 1.],
       [0., 0., 1., 1., 0., 0.],
       [1., 1., 0., 0., 1., 1.]])

In [ ]:
arr=np.array([1.1,2.3,4.2,5.6])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 4 5]
int32
